### ISSUE TITLE
Display a webpage

### ISSUE THREAD

**Issue by EclipseOfficeTech** [WilliamAmbrozic/Solana-NFT-Scripts#3]
Would love a quick guide or some guidance as to how to possibly show : https://github.com/WilliamAmbrozic/Solana-NFT-Scripts/blob/main/holder_distribution.ts

As a webpage.

**Comment by WilliamAmbrozic** [comment]
Good Afternoon 😄,

**What the script does at its core:** Essentially the holder distribution script iterates through each mint address of the given NFT collection and looks for the owner. It then adds each owner to a hashmap with the owner address as the key and the number of times the address has been seen as the value. The script then displays a small snapshot of the holder distribution.

**Utilizing as a web app:** The exact details of turning this into a web app would depend on your chosen development stack. For example, you could construct the hashmap daily on a Node.js server (a backend) and then serve it to some frontend (Angular, React, etc.). Given the hashmap, it would then simply be an issue of displaying the holder distribution based on the hashmap keys and values. Perhaps you use a table showing all owner addresses (keys) followed by another table column showing their holdings (values). The way you choose to display this data is beyond the script (i.e. statistical analysis, etc.).

I hope this helps,

William Ambrozic

**Comment by WilliamAmbrozic** [comment]
An amazing example can be found [here](https://www.br1percenters.com/owners) by [br1Percenters](https://twitter.com/BR1PERCENTERS).

**Comment by EclipseOfficeTech** [comment]
Stack is node, nuxtjs but the example given is pretty much what I was looking for. so will take a look and see what can be put together.
